export { FileItem } from './ui/FileItem/FileItem'
export { getCurrentId } from './model/selectors/getCurrentId/getCurrentId'
export { getFiles } from './model/selectors/getFiles/getFiles'
export { fileActions, fileReducer } from './model/slice/fileSlice'
export type { FileSchema, FileType, IFile } from './model/types/file'
